### ISSUE TITLE
Pickling 'threshold' function fails

### ISSUE THREAD

**Issue by twalenczyk** [notmattmoore/quantum-algorithms#9] opened 2019-09-26 20:16 UTC
The following code

```
from itertools import *
import ualgebra as UA
import post_ops as PO
.
.
.
Ops = PO.named_clone("DM")
n = 4
Dn = [ list(a) for a in product([0,1], repeat=n) ]
Theta, Theta_gens = UA.rand_cong(Dn, Ops, Progress=False)
```
throws a pickling error:
```
Traceback (most recent call last):
  File "sum.py", line 71, in <module>
    A, A_gens = UA.rand_subalg(Dn, Ops, Progress=False)
  File "/Users/twalen/Desktop/Technical/quantum_research/quantum-algorithms/simon-experiment/ualgebra.py", line 476, in rand_subalg
    S = subalg_gen(G, Ops, MaxNew=MaxNew, Progress=Progress)
  File "/Users/twalen/Desktop/Technical/quantum_research/quantum-algorithms/simon-experiment/ualgebra.py", line 371, in subalg_gen
    G_newer = single_closure(G_old, G_new, Ops, MaxNew=MaxNew, Progress=Progress, Search=Search)
  File "/Users/twalen/Desktop/Technical/quantum_research/quantum-algorithms/simon-experiment/ualgebra.py", line 335, in single_closure
    for args_index, result in enumerate(pool.imap(op, args_all, chunksize=1000)):
  File "/Users/twalen/anaconda3/lib/python3.7/multiprocessing/pool.py", line 325, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/Users/twalen/anaconda3/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
  File "/Users/twalen/anaconda3/lib/python3.7/multiprocessing/pool.py", line 431, in _handle_tasks
    put(task)
  File "/Users/twalen/anaconda3/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/Users/twalen/anaconda3/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
AttributeError: Can't pickle local object 'threshold.<locals>.thnk'
```

The issue is due to the embedding of 'thnk' inside 'threshold':
```
def threshold(k, n): 
   """
   Return the threshold function (the UA.Operator version of it) th_k^n defined
   by
 
     th_k^n(x1, ..., xn) = 1   if #{i | x_i = 1} >= k,
                           0   else
   """
   def thnk(*args, k=k, n=n):
     if args.count(1) >= k:
       return 1
     return 0
   op_thnk = UA.Operation(thnk, n, "th_" + str(k) + "^" + str(n))
   return op_thnk
```

Pickle only pickles "top-level" objects, functions, etc.; so, it won't pickle 'thnk.'

**Comment by twalenczyk** [comment] 2019-09-26 22:10
I expected the classic `import dill as pickle` trick to work. But, it didn't (which is unfortunate). It's clear to me now that the issue goes much deeper. The Pool class pickles objects (on full display in the multiprocessing library in Python's repository).

**Comment by notmattmoore** [comment] 2019-09-27 17:15
I have run into this issue before, and it has always been completely opaque. I'll have to remember what I did to fix it last time.

**Comment by notmattmoore** [comment] 2019-09-27 21:59
It looks like pickling only works for top-level defined functions. There are suggestions online about using dill instead, but the pickling is happening inside the multiprocessing module, so we would need to modify the module.

It looks like there's another multiprocessing framework called pathos that uses dill out of the box. It's going to be a bit of work to change ualgebra over to a different framework, and I'm not sure that it will fix the problem.

I suggest one of us write some test code to reproduce the error multiprocessing throws and then modify the test code to use pathos. This at least avoids making changes to ualgebra until we have a sense whether pathos will fix the problem.

**Comment by twalenczyk** [comment] 2019-10-02 16:12
Looking at the pathos repo, I'm not sure the pathos `imap` make use of `chunksize` like the standard python one does. **UPDATE** That being said, I'm not seeing performance degradation.

**Comment by twalenczyk** [comment] 2019-10-02 16:16
Also, `sum.py` seems to hang now.

**Comment by notmattmoore** [comment] 2019-10-02 23:38
I just merged in the changes. Looks like using pathos fixed it!

**Closed as completed by notmattmoore** 2019-10-02 23:38 UTC
